### ISSUE TITLE
License Please

### ISSUE THREAD

**Issue by lpurdy01** [spoter368/os3m-firmware#2]
Could you please add a `LICENSE.txt` file to this repo? 

Whatever license you want, I see you did GPLv3 on the software repo. 

Just ordered my boards and am looking forward to contributing!

**Comment by spoter368** [comment]
Done! I am a little worried about "Core\Src\STM_LDC16xx.c" file, as I got it from someone else who licensed it under BSD 3 clause, (and then modified it quite a bit) but they are compatible, correct?

**Comment by lpurdy01** [comment]
GPT-4 says it is, and that is usually good enough for me. It looks like you kept the license notice in the file, so should be good!
