### ISSUE TITLE
Not working, what am I missing?

### ISSUE THREAD

**Issue by Tropaion** [spoter368/os3m-firmware#5]
Hello,
I just got my assembled PCB from jlc and successfully programmed and assembled it.
The mouse is correctly recognized as an controller, but I don't see any axis data in the windows gamecontroller setup.
Do I need to calibrate something?
Since I'm not from the US I used two-eurocent-coins which fit perfectly and is copper plated steel, which I hoped would work.
Also, I'm not sure if it should be so, but the spring is very sensitive. With the smallest tremor, the knob slightly vibrates.
I hope someone has ideas.

**Comment by spoter368** [comment]
I need more details to help you debug. Can you clarify what you mean by “ The mouse is correctly recognized as a controller, but I don't see any axis data in the windows gamecontroller setup. “?

There is no calibration you need to do. Is the mouse perhaps placed on a conductive surface like a steel table that is saturating the sensors?

**Comment by Tropaion** [comment]
> Is the mouse perhaps placed on a conductive surface like a steel table that is saturating the sensors?

No, it is placed on an wooden table.

> “ The mouse is correctly recognized as a controller, but I don't see any axis data in the windows gamecontroller setup. “?
PC recognizes the mouse, but I don't get any input.
![image](https://github.com/spoter368/os3m-firmware/assets/6797663/aa1ac3b7-68c0-4c4a-81c6-a13b1bcb4652)
No input at "testing".

**Comment by spoter368** [comment]
Does it move at all when you place any conductive object within range of the coils?

**Comment by Tropaion** [comment]
No, nothing moves. Just now I tried my second PCB I got and this one works, even though it's unusable because the spring is way to flexible and always wobbles.
Looks like I have to thorougly check the coils of pcb, because programming and usb works.
BTW  @spoter368 what material did you use for the spring/how did you print it? I used PETG but looks like it's not useable.

**Comment by BoraMD** [comment]
Have you managed to find out what was the issue on pcb? I got same problem as yours pc communicates with board sees as controller but no movement at all. Is there a programing, interference issues or faulty pcb, solders i want to find out.

**Comment by Tropaion** [comment]
No, sorry, I didn't.
